vich_uploader:
    db_driver: orm
    mappings:
        club_image:
            uri_prefix: /images/clubs
            upload_destination: '%kernel.project_dir%/public/images/clubs'
            namer: Vich\UploaderBundle\Naming\OrignameNamer
            delete_on_remove: true
            delete_on_update: true
            inject_on_load: true