<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20230503165002 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE Adherant DROP FOREIGN KEY FK_6EAC3AEA36BCDB3D');
        $this->addSql('ALTER TABLE Adherant DROP FOREIGN KEY FK_6EAC3AEA9663D2C8');
        $this->addSql('ALTER TABLE Adherant DROP FOREIGN KEY FK_6EAC3AEA94F96677');
        $this->addSql('ALTER TABLE Adherant DROP FOREIGN KEY FK_6EAC3AEAE8D997BE');
        $this->addSql('ALTER TABLE Adherant ADD CONSTRAINT FK_6EAC3AEA36BCDB3D FOREIGN KEY (equipeId) REFERENCES Equipe (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE Adherant ADD CONSTRAINT FK_6EAC3AEA9663D2C8 FOREIGN KEY (categrieId) REFERENCES Categorie (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE Adherant ADD CONSTRAINT FK_6EAC3AEA94F96677 FOREIGN KEY (Deme_categorieId) REFERENCES DemeCategorie (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE Adherant ADD CONSTRAINT FK_6EAC3AEAE8D997BE FOREIGN KEY (supervisorId) REFERENCES Supervisor (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE Categorie DROP FOREIGN KEY FK_CB8C54971FB658F6');
        $this->addSql('ALTER TABLE Categorie ADD CONSTRAINT FK_CB8C54971FB658F6 FOREIGN KEY (clubId) REFERENCES Club (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE Cours DROP FOREIGN KEY FK_3C0BA3981FB658F6');
        $this->addSql('ALTER TABLE Cours DROP FOREIGN KEY FK_3C0BA398880019E7');
        $this->addSql('ALTER TABLE Cours ADD CONSTRAINT FK_3C0BA3981FB658F6 FOREIGN KEY (clubId) REFERENCES Club (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE Cours ADD CONSTRAINT FK_3C0BA398880019E7 FOREIGN KEY (niveauId) REFERENCES Niveau (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE Cycle DROP FOREIGN KEY FK_7147FE971FB658F6');
        $this->addSql('ALTER TABLE Cycle DROP FOREIGN KEY FK_7147FE971347B425');
        $this->addSql('ALTER TABLE Cycle ADD CONSTRAINT FK_7147FE971FB658F6 FOREIGN KEY (clubId) REFERENCES Club (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE Cycle ADD CONSTRAINT FK_7147FE971347B425 FOREIGN KEY (coursId) REFERENCES Cours (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE DemeCategorie DROP FOREIGN KEY FK_43BAF2951FB658F6');
        $this->addSql('ALTER TABLE DemeCategorie ADD CONSTRAINT FK_43BAF2951FB658F6 FOREIGN KEY (clubId) REFERENCES Club (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE DossierMedical DROP FOREIGN KEY FK_6440F5B477DEC5A');
        $this->addSql('ALTER TABLE DossierMedical DROP FOREIGN KEY FK_6440F5B41FB658F6');
        $this->addSql('ALTER TABLE DossierMedical ADD CONSTRAINT FK_6440F5B492F9C8F8 FOREIGN KEY (adherantid) REFERENCES Adherant (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE DossierMedical ADD CONSTRAINT FK_6440F5B41FB658F6 FOREIGN KEY (clubId) REFERENCES Club (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE Equipe DROP FOREIGN KEY FK_23E5BF237EF1F90C');
        $this->addSql('ALTER TABLE Equipe DROP FOREIGN KEY FK_23E5BF23880019E7');
        $this->addSql('ALTER TABLE Equipe DROP FOREIGN KEY FK_23E5BF231FB658F6');
        $this->addSql('ALTER TABLE Equipe DROP FOREIGN KEY FK_23E5BF23911B7CB9');
        $this->addSql('ALTER TABLE Equipe ADD CONSTRAINT FK_23E5BF237EF1F90C FOREIGN KEY (coachId) REFERENCES Coach (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE Equipe ADD CONSTRAINT FK_23E5BF23880019E7 FOREIGN KEY (niveauId) REFERENCES Niveau (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE Equipe ADD CONSTRAINT FK_23E5BF231FB658F6 FOREIGN KEY (clubId) REFERENCES Club (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE Equipe ADD CONSTRAINT FK_23E5BF23911B7CB9 FOREIGN KEY (doctorId) REFERENCES Doctor (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE Mesure DROP FOREIGN KEY FK_58B76B46911B7CB9');
        $this->addSql('ALTER TABLE Mesure DROP FOREIGN KEY FK_58B76B461FB658F6');
        $this->addSql('ALTER TABLE Mesure DROP FOREIGN KEY FK_58B76B463AC4B029');
        $this->addSql('ALTER TABLE Mesure ADD CONSTRAINT FK_58B76B46911B7CB9 FOREIGN KEY (doctorId) REFERENCES Doctor (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE Mesure ADD CONSTRAINT FK_58B76B461FB658F6 FOREIGN KEY (clubId) REFERENCES Club (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE Mesure ADD CONSTRAINT FK_58B76B463AC4B029 FOREIGN KEY (dossier_medicalId) REFERENCES DossierMedical (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE Niveau DROP FOREIGN KEY FK_4C73F65D1FB658F6');
        $this->addSql('ALTER TABLE Niveau DROP FOREIGN KEY FK_4C73F65D438B1980');
        $this->addSql('ALTER TABLE Niveau ADD CONSTRAINT FK_4C73F65D1FB658F6 FOREIGN KEY (clubId) REFERENCES Club (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE Niveau ADD CONSTRAINT FK_4C73F65D438B1980 FOREIGN KEY (sectionId) REFERENCES Section (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE Note DROP FOREIGN KEY FK_6F8F552AA22540BD');
        $this->addSql('ALTER TABLE Note DROP FOREIGN KEY FK_6F8F552A1FB658F6');
        $this->addSql('ALTER TABLE Note DROP FOREIGN KEY FK_6F8F552ACA742475');
        $this->addSql('ALTER TABLE Note DROP FOREIGN KEY FK_6F8F552A77DEC5A');
        $this->addSql('ALTER TABLE Note ADD CONSTRAINT FK_6F8F552AA22540BD FOREIGN KEY (testeId) REFERENCES Teste (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE Note ADD CONSTRAINT FK_6F8F552A1FB658F6 FOREIGN KEY (clubId) REFERENCES Club (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE Note ADD CONSTRAINT FK_6F8F552ACA742475 FOREIGN KEY (objectifId) REFERENCES Objectif (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE Note ADD CONSTRAINT FK_6F8F552A77DEC5A FOREIGN KEY (adherantId) REFERENCES Adherant (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE Objectif DROP FOREIGN KEY FK_1B8E0A078105C8EF');
        $this->addSql('ALTER TABLE Objectif DROP FOREIGN KEY FK_1B8E0A071FB658F6');
        $this->addSql('ALTER TABLE Objectif ADD CONSTRAINT FK_1B8E0A078105C8EF FOREIGN KEY (cycleId) REFERENCES Cycle (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE Objectif ADD CONSTRAINT FK_1B8E0A071FB658F6 FOREIGN KEY (clubId) REFERENCES Club (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE Seance DROP FOREIGN KEY FK_D8D1F8388105C8EF');
        $this->addSql('ALTER TABLE Seance DROP FOREIGN KEY FK_D8D1F8381FB658F6');
        $this->addSql('ALTER TABLE Seance DROP FOREIGN KEY FK_D8D1F83836BCDB3D');
        $this->addSql('ALTER TABLE Seance ADD CONSTRAINT FK_D8D1F8388105C8EF FOREIGN KEY (cycleId) REFERENCES Cycle (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE Seance ADD CONSTRAINT FK_D8D1F8381FB658F6 FOREIGN KEY (clubId) REFERENCES Club (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE Seance ADD CONSTRAINT FK_D8D1F83836BCDB3D FOREIGN KEY (equipeId) REFERENCES Equipe (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE Section DROP FOREIGN KEY FK_E2CE43731FB658F6');
        $this->addSql('ALTER TABLE Section ADD CONSTRAINT FK_E2CE43731FB658F6 FOREIGN KEY (clubId) REFERENCES Club (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE Teste DROP FOREIGN KEY FK_2775660B1FB658F6');
        $this->addSql('ALTER TABLE Teste DROP FOREIGN KEY FK_2775660B36BCDB3D');
        $this->addSql('ALTER TABLE Teste DROP FOREIGN KEY FK_2775660B8105C8EF');
        $this->addSql('ALTER TABLE Teste ADD CONSTRAINT FK_2775660B1FB658F6 FOREIGN KEY (clubId) REFERENCES Club (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE Teste ADD CONSTRAINT FK_2775660B36BCDB3D FOREIGN KEY (equipeId) REFERENCES Equipe (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE Teste ADD CONSTRAINT FK_2775660B8105C8EF FOREIGN KEY (cycleId) REFERENCES Cycle (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE user DROP FOREIGN KEY FK_8D93D6491FB658F6');
        $this->addSql('ALTER TABLE user ADD CONSTRAINT FK_8D93D6491FB658F6 FOREIGN KEY (clubId) REFERENCES Club (id) ON DELETE CASCADE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE Adherant DROP FOREIGN KEY FK_6EAC3AEA9663D2C8');
        $this->addSql('ALTER TABLE Adherant DROP FOREIGN KEY FK_6EAC3AEA36BCDB3D');
        $this->addSql('ALTER TABLE Adherant DROP FOREIGN KEY FK_6EAC3AEA94F96677');
        $this->addSql('ALTER TABLE Adherant DROP FOREIGN KEY FK_6EAC3AEAE8D997BE');
        $this->addSql('ALTER TABLE Adherant ADD CONSTRAINT FK_6EAC3AEA9663D2C8 FOREIGN KEY (categrieId) REFERENCES Categorie (id)');
        $this->addSql('ALTER TABLE Adherant ADD CONSTRAINT FK_6EAC3AEA36BCDB3D FOREIGN KEY (equipeId) REFERENCES Equipe (id)');
        $this->addSql('ALTER TABLE Adherant ADD CONSTRAINT FK_6EAC3AEA94F96677 FOREIGN KEY (Deme_categorieId) REFERENCES DemeCategorie (id)');
        $this->addSql('ALTER TABLE Adherant ADD CONSTRAINT FK_6EAC3AEAE8D997BE FOREIGN KEY (supervisorId) REFERENCES Supervisor (id)');
        $this->addSql('ALTER TABLE Categorie DROP FOREIGN KEY FK_CB8C54971FB658F6');
        $this->addSql('ALTER TABLE Categorie ADD CONSTRAINT FK_CB8C54971FB658F6 FOREIGN KEY (clubId) REFERENCES Club (id)');
        $this->addSql('ALTER TABLE Cours DROP FOREIGN KEY FK_3C0BA3981FB658F6');
        $this->addSql('ALTER TABLE Cours DROP FOREIGN KEY FK_3C0BA398880019E7');
        $this->addSql('ALTER TABLE Cours ADD CONSTRAINT FK_3C0BA3981FB658F6 FOREIGN KEY (clubId) REFERENCES Club (id)');
        $this->addSql('ALTER TABLE Cours ADD CONSTRAINT FK_3C0BA398880019E7 FOREIGN KEY (niveauId) REFERENCES Niveau (id)');
        $this->addSql('ALTER TABLE Cycle DROP FOREIGN KEY FK_7147FE971347B425');
        $this->addSql('ALTER TABLE Cycle DROP FOREIGN KEY FK_7147FE971FB658F6');
        $this->addSql('ALTER TABLE Cycle ADD CONSTRAINT FK_7147FE971347B425 FOREIGN KEY (coursId) REFERENCES Cours (id)');
        $this->addSql('ALTER TABLE Cycle ADD CONSTRAINT FK_7147FE971FB658F6 FOREIGN KEY (clubId) REFERENCES Club (id)');
        $this->addSql('ALTER TABLE DemeCategorie DROP FOREIGN KEY FK_43BAF2951FB658F6');
        $this->addSql('ALTER TABLE DemeCategorie ADD CONSTRAINT FK_43BAF2951FB658F6 FOREIGN KEY (clubId) REFERENCES Club (id)');
        $this->addSql('ALTER TABLE DossierMedical DROP FOREIGN KEY FK_6440F5B492F9C8F8');
        $this->addSql('ALTER TABLE DossierMedical DROP FOREIGN KEY FK_6440F5B41FB658F6');
        $this->addSql('ALTER TABLE DossierMedical ADD CONSTRAINT FK_6440F5B477DEC5A FOREIGN KEY (adherantId) REFERENCES Adherant (id)');
        $this->addSql('ALTER TABLE DossierMedical ADD CONSTRAINT FK_6440F5B41FB658F6 FOREIGN KEY (clubId) REFERENCES Club (id)');
        $this->addSql('ALTER TABLE Equipe DROP FOREIGN KEY FK_23E5BF23880019E7');
        $this->addSql('ALTER TABLE Equipe DROP FOREIGN KEY FK_23E5BF23911B7CB9');
        $this->addSql('ALTER TABLE Equipe DROP FOREIGN KEY FK_23E5BF231FB658F6');
        $this->addSql('ALTER TABLE Equipe DROP FOREIGN KEY FK_23E5BF237EF1F90C');
        $this->addSql('ALTER TABLE Equipe ADD CONSTRAINT FK_23E5BF23880019E7 FOREIGN KEY (niveauId) REFERENCES Niveau (id)');
        $this->addSql('ALTER TABLE Equipe ADD CONSTRAINT FK_23E5BF23911B7CB9 FOREIGN KEY (doctorId) REFERENCES Doctor (id)');
        $this->addSql('ALTER TABLE Equipe ADD CONSTRAINT FK_23E5BF231FB658F6 FOREIGN KEY (clubId) REFERENCES Club (id)');
        $this->addSql('ALTER TABLE Equipe ADD CONSTRAINT FK_23E5BF237EF1F90C FOREIGN KEY (coachId) REFERENCES Coach (id)');
        $this->addSql('ALTER TABLE Mesure DROP FOREIGN KEY FK_58B76B46911B7CB9');
        $this->addSql('ALTER TABLE Mesure DROP FOREIGN KEY FK_58B76B461FB658F6');
        $this->addSql('ALTER TABLE Mesure DROP FOREIGN KEY FK_58B76B463AC4B029');
        $this->addSql('ALTER TABLE Mesure ADD CONSTRAINT FK_58B76B46911B7CB9 FOREIGN KEY (doctorId) REFERENCES Doctor (id)');
        $this->addSql('ALTER TABLE Mesure ADD CONSTRAINT FK_58B76B461FB658F6 FOREIGN KEY (clubId) REFERENCES Club (id)');
        $this->addSql('ALTER TABLE Mesure ADD CONSTRAINT FK_58B76B463AC4B029 FOREIGN KEY (dossier_medicalId) REFERENCES DossierMedical (id)');
        $this->addSql('ALTER TABLE Niveau DROP FOREIGN KEY FK_4C73F65D1FB658F6');
        $this->addSql('ALTER TABLE Niveau DROP FOREIGN KEY FK_4C73F65D438B1980');
        $this->addSql('ALTER TABLE Niveau ADD CONSTRAINT FK_4C73F65D1FB658F6 FOREIGN KEY (clubId) REFERENCES Club (id)');
        $this->addSql('ALTER TABLE Niveau ADD CONSTRAINT FK_4C73F65D438B1980 FOREIGN KEY (sectionId) REFERENCES Section (id)');
        $this->addSql('ALTER TABLE Note DROP FOREIGN KEY FK_6F8F552ACA742475');
        $this->addSql('ALTER TABLE Note DROP FOREIGN KEY FK_6F8F552AA22540BD');
        $this->addSql('ALTER TABLE Note DROP FOREIGN KEY FK_6F8F552A1FB658F6');
        $this->addSql('ALTER TABLE Note DROP FOREIGN KEY FK_6F8F552A77DEC5A');
        $this->addSql('ALTER TABLE Note ADD CONSTRAINT FK_6F8F552ACA742475 FOREIGN KEY (objectifId) REFERENCES Objectif (id)');
        $this->addSql('ALTER TABLE Note ADD CONSTRAINT FK_6F8F552AA22540BD FOREIGN KEY (testeId) REFERENCES Teste (id)');
        $this->addSql('ALTER TABLE Note ADD CONSTRAINT FK_6F8F552A1FB658F6 FOREIGN KEY (clubId) REFERENCES Club (id)');
        $this->addSql('ALTER TABLE Note ADD CONSTRAINT FK_6F8F552A77DEC5A FOREIGN KEY (adherantId) REFERENCES Adherant (id)');
        $this->addSql('ALTER TABLE Objectif DROP FOREIGN KEY FK_1B8E0A078105C8EF');
        $this->addSql('ALTER TABLE Objectif DROP FOREIGN KEY FK_1B8E0A071FB658F6');
        $this->addSql('ALTER TABLE Objectif ADD CONSTRAINT FK_1B8E0A078105C8EF FOREIGN KEY (cycleId) REFERENCES Cycle (id)');
        $this->addSql('ALTER TABLE Objectif ADD CONSTRAINT FK_1B8E0A071FB658F6 FOREIGN KEY (clubId) REFERENCES Club (id)');
        $this->addSql('ALTER TABLE Seance DROP FOREIGN KEY FK_D8D1F83836BCDB3D');
        $this->addSql('ALTER TABLE Seance DROP FOREIGN KEY FK_D8D1F8388105C8EF');
        $this->addSql('ALTER TABLE Seance DROP FOREIGN KEY FK_D8D1F8381FB658F6');
        $this->addSql('ALTER TABLE Seance ADD CONSTRAINT FK_D8D1F83836BCDB3D FOREIGN KEY (equipeId) REFERENCES Equipe (id)');
        $this->addSql('ALTER TABLE Seance ADD CONSTRAINT FK_D8D1F8388105C8EF FOREIGN KEY (cycleId) REFERENCES Cycle (id)');
        $this->addSql('ALTER TABLE Seance ADD CONSTRAINT FK_D8D1F8381FB658F6 FOREIGN KEY (clubId) REFERENCES Club (id)');
        $this->addSql('ALTER TABLE Section DROP FOREIGN KEY FK_E2CE43731FB658F6');
        $this->addSql('ALTER TABLE Section ADD CONSTRAINT FK_E2CE43731FB658F6 FOREIGN KEY (clubId) REFERENCES Club (id)');
        $this->addSql('ALTER TABLE Teste DROP FOREIGN KEY FK_2775660B36BCDB3D');
        $this->addSql('ALTER TABLE Teste DROP FOREIGN KEY FK_2775660B8105C8EF');
        $this->addSql('ALTER TABLE Teste DROP FOREIGN KEY FK_2775660B1FB658F6');
        $this->addSql('ALTER TABLE Teste ADD CONSTRAINT FK_2775660B36BCDB3D FOREIGN KEY (equipeId) REFERENCES Equipe (id)');
        $this->addSql('ALTER TABLE Teste ADD CONSTRAINT FK_2775660B8105C8EF FOREIGN KEY (cycleId) REFERENCES Cycle (id)');
        $this->addSql('ALTER TABLE Teste ADD CONSTRAINT FK_2775660B1FB658F6 FOREIGN KEY (clubId) REFERENCES Club (id)');
        $this->addSql('ALTER TABLE user DROP FOREIGN KEY FK_8D93D6491FB658F6');
        $this->addSql('ALTER TABLE user ADD CONSTRAINT FK_8D93D6491FB658F6 FOREIGN KEY (clubId) REFERENCES Club (id)');
    }
}
